project:
  type: website

# website:
#   navbar:
#     left:
#       - href: note.qmd

format:
  html:
    theme: cosmo
    css: static/css/font.css
    toc: true
    include-before-body: static/js/font.html
    self-contained-math: true
  pdf:
    include-in-header: 
      text: |
        \usepackage{ctex}
        \usepackage{amsthm,mathrsfs}
        \usepackage{float}
        \let\origfigure\figure
        \let\endorigfigure\endfigure
        \renewenvironment{figure}[1][2] {
            \expandafter\origfigure\expandafter[H]
        } {
            \endorigfigure
        }
    include-before-body:
      text: |
        \captionsetup{justification=raggedright,singlelinecheck=false}


execute:
  freeze: auto



