project:
  type: website

# website:
#   navbar:
#     left:
#       - href: note.qmd

format:
  html:
    theme: cosmo
    css: static/css/font.css
    toc: true
    include-before-body: static/js/font.html
    self-contained-math: true
  pdf:
    include-in-header: 
      text: |
        \usepackage{ctex}
        \usepackage{indentfirst}


execute:
  freeze: auto



