project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: note.qmd
        text: Note
      - href: slides.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



