project:
  type: website

website:
  title: "snow and rain"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: note.qmd
        text: Note
      - href: slides.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: static/css/font.css
    toc: true
    include-before-body: static/js/font.html


execute:
  freeze: auto



