---
title: "富集分析"
date: "2024-07-02"
format:
    html: 
      self-contained: false
      grid: 
        margin-width: 350px
execute: 
  echo: true
toc: true
reference-location: margin
citation-location: margin
---

假设共有4条通路分别为A, B, C, D. 其中A, B, C通路含有分别有10个基因，D通路有26个基因。4条通路， 即整个背景基因集总共的基因（去重）数目为26。

```{r}
set.seed(2024)
all_pathway <- list(
  A = sample(letters, 10),
  B = sample(letters, 10),
  C = sample(letters, 12),
  D = letters
)
```


```{r}
all_pathway[["A"]]
(m <- all_pathway[["A"]] |> length()) # A通路基因数目
(n <- 26 - 10) # 非A通路基因数目
```

假设我们获得了差异基因gene, 共5个。
```{r}
gene <- c("a", "b", "c", "e", "f")

# 属于A通路的差异基因数目 -1
(q <- intersect(all_pathway[["A"]], gene) |> length() - 1)
(k <- length(gene)) # 差异基因数目
```

我们所做的检验是：在26个基因中，有10个是A通路的基因，现在我们在26个基因中不放回的抽取5个基因，这5个基因中有2个是属于A通路的基因。从概率上， 我们从26个中抽取5个，其中属于A通路的基因数目 > 2 - 1的概率是多少(如果p < 0.05, 则说明这是小概率事件，但是却发生了；则说明这条通路是过度呈现的, over representation)）。

```{r}
suppressMessages(all_pathway <- easybio::list2dt(all_pathway))
pvalue <- phyper(q, m, n, k, lower.tail = FALSE) # 超几何分布检验

y <- clusterProfiler::enricher(
  gene,
  TERM2GENE = all_pathway,
  pAdjustMethod = "BH",
  pvalueCutoff = 1,
  qvalueCutoff = 1,
  minGSSize = 0
) # 用于富集分析的一个经典的R包，其背后的原理实际上也是超几何分布检验。
data.table::setDT(y@result)[]
```

从结果可以看到A通路的p值计算结果，两者是一致的。其中 $GeneRation = (q + 1)/k, BgRation = m / (m + n)$

```{r}
# A 通路的GeneRation 以及 BgRation
y@result[.("A"), pvalue, on = .(ID)] == pvalue
(GeneRation <- paste0(q + 1, "/", k))
(BgRation <- paste0(m, "/", m + n))
```