project:
  output-dir: _output

toc: true
number-sections: true
format:
  html:
    embed-resources: false
    css: styles.css
    grid:
      margin-width: 350px
reference-location: margin
citation-location: margin
execute: 
  echo: fenced
  


