---
title: Survival Analysis
date: '2024-10-12'
---

# Current Life Table

现时寿命表是加上同时出生的一代人，按照某年某地实际人口年龄别死亡率计算出的年龄别死亡率计算出的年龄别死亡率陆续死亡，直到全部人口死完为止，用寿命表的方法计算出这一代人在不同年龄组的“死亡人数”和刚满某年龄时的“尚存人数”以及“预期寿命”等寿命表指标。

每一组是是左闭右开的区间 $[x, x + n)$. 考虑从横断面数据获得以下指标：

1. $x$: exact age.
2. $_{n}P_x$: $x$ 岁组的平均人口数, $x$ 表示年龄组下限，$n$ 表示组距。
3. $_{n}D_x$: $x$ 岁组实际死亡人数。
4. $_{n}m_x$: $\frac{_{n}D_x}{_{n}P_x}$.


假定同时出生的一代人为10万人，那么其初期人数 $l_0 = 100000$. 则有：

1. 0岁组年龄别死亡概率为 $q_0 = 婴儿死亡率 = \frac{某年婴儿死亡数}{某年活产数}$。中间组年龄别死亡概率 $_{n}q_x = \frac{2n \cdot {_{n}m_x}}{2 + {n \cdot _{n}m_x}}$。最后一组死亡概率为1.
2. person-year of survival: $L_0 = l_1 + a_0 \cdot d_0$; 中间组 $_{n}L_x = \frac{l_x + l_{x+n}}{2} \cdot n$; 最后一组 $L_{\omega} = \frac{l_\omega}{m_\omega}$

由初期的10万人，以及每个组的年龄别死亡概率可计算得到每个组的理论死亡人数，进而得到每个组的初期人数 $l_{x+n} = l_x - d_x$ ；由此，可计算得到每个组的人年数，从最后一组开始累加即得到每个组生存人总年数 $T_x = \sum{_{n}L_x}$,  进而求得 预期寿命 $e_x = \frac{T_x}{l_x}$.

去死因寿命表与一般寿命表的差异在于其根据去死因生存概率计算每组的期初人数。

1. $_{n}r_x^{-i} = \frac{_{n}D_x - _{n}D_x^{-i}}{_{n}D_x}$.
2. $_{n}P_x^{-i} = (_{n}P_x)^{_{n}r_{x}^{-i}}$.
3. $l_{x + n}^{-i} = l_x^{-i} \cdot _{n}p_{x}^{-i}$.
4. $_{n}d_{x}^{-i} = l_x^{-i} - l_{n+x}^{-i}$

# Survival Analysis

直接观察满 $n$ 年的人数中活满 n 年的比率。其计算公式为：

$n年生存率 = \frac{活满n年的人数}{观察满n年的人数} \cdot 100 \%$

考虑 $x, L_x, W_x, D_x$ 分别为随访年数，期初观察人数，期内失访人数，期内死亡人数，那么有：


1. $L_{x + 1} = L_x - W_x - D_x$.
1. $N_x = L_x - \frac{W_x}{2}$. 校正人数，该公式假设每个失访者在这个区间内被随访的时间是区间长度的一半，那么 $N_x$ 相当于是实际随访的人年数。
2. $q_x = \frac{D_x}{N_x}$. 死亡概率，表示活满 $x$ 年的人在第二年死亡的概率。
3. $p_x = 1 - q_x$. 生存概率，表示活满 $x$ 年的人再活一年的概率。

那么，其 $n$ 年生存率：

$$
\begin{aligned}
_{n}P_{0} =& \prod_{x = 0}^{n-1} p_x \\
S_{_{n}P_{0}} =& _{n}P_{0} \cdot \sqrt{\sum_{i = 0}^{n-1}{\frac{q_i}{p_i \cdot N_i}}}
\end{aligned}
$$



